<script setup lang="ts">
import {computed,onMounted,onBeforeUnmount,ref,watch} from 'vue';
import ValueFilters from './components/ValueFilters.vue';
import ValueList from './components/ValueList.vue';
import ValueDialog from './components/ValueDialog.vue';
import DataStatusView from './components/DataStatusView.vue';
import {ValuePreferencesSchema,type Catalog,type Plan,type ValuePreferences} from '../shared/schema';
import {planMatchesQuery,planModelNames,type ValueResult,type ValueQuote} from '../shared/value';
import {latestVerifiedAt} from '../shared/recommend';
import {t,td,toggleLocale} from './i18n';
import type {UiKey} from './locales/ui';
const tab=ref('value'),catalog=ref<Catalog|null>(null),status=ref<any>(null),error=ref(''),busy=ref(true),now=ref(Date.now());
const prefs=ref<ValuePreferences>(ValuePreferencesSchema.parse({})),results=ref<ValueResult|null>(null),selected=ref<string[]>([]),detail=ref<ValueQuote[]>([]),detailPlan=ref<Plan|null>(null),method=ref(false),toast=ref('');
let request=0,debounce:ReturnType<typeof setTimeout>,clock:ReturnType<typeof setInterval>,refresh:ReturnType<typeof setInterval>,toastTimer:ReturnType<typeof setTimeout>;
const detailCatalog=computed(()=>catalog.value);
const hasDialog=computed(()=>method.value||detail.value.length>0||detailPlan.value!==null);
const comparable=computed(()=>results.value?.quotes.filter(q=>selected.value.includes(q.id)&&Date.parse(q.validUntil)>now.value)??[]);
const checkedDate=computed(()=>{const latest=catalog.value?latestVerifiedAt(catalog.value):null;return latest?new Date(latest).toLocaleDateString('en-GB',{month:'2-digit',day:'2-digit',timeZone:'Asia/Taipei'}).split('/').reverse().join('.'):'—';});
async function api(path:string,options?:RequestInit){const res=await fetch(path,options);const body=await res.json();if(!res.ok)throw new Error(body.error??t('error.service'));return body;}
async function search(){const id=++request;busy.value=true;try{const validated=ValuePreferencesSchema.parse(prefs.value);const fetchValue=(value:ValuePreferences)=>api('/api/v1/value',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)}) as Promise<ValueResult>;const [data,unfiltered]=await Promise.all([fetchValue(validated),validated.query.trim()?fetchValue({...validated,query:''}):Promise.resolve(null)]);if(id!==request)return;const source=unfiltered??data;const currentCatalog=catalog.value;results.value=currentCatalog?{...data,unknown:[...new Map([...data.unknown,...source.unknown].map(q=>[q.plan.id,q])).values()].filter(q=>planMatchesQuery(currentCatalog,q.plan,validated.query)||td(q.plan.name).toLowerCase().includes(validated.query.toLowerCase().trim())).map(q=>({...q,modelNames:planModelNames(currentCatalog,q.plan)}))}:data;error.value='';const url=new URL(location.href);const defaults=ValuePreferencesSchema.parse({});url.search='';for(const [key,value] of Object.entries(validated))if(value!==defaults[key as keyof ValuePreferences]&&value!==null)url.searchParams.set(key,String(value));history.replaceState(null,'',url);}catch(e){if(id===request)error.value=e instanceof Error?e.message:t('error.load');}finally{if(id===request)busy.value=false;}}
async function load(){try{[catalog.value,status.value]=await Promise.all([api('/api/v1/catalog?includeExpired=true'),api('/api/v1/status')]);}catch{error.value=t('error.unreachable');}await search();}
function reset(){prefs.value=ValuePreferencesSchema.parse({});}
function close(){detail.value=[];detailPlan.value=null;method.value=false;}
function compare(q:ValueQuote){if(!selected.value.includes(q.id)&&selected.value.length<3)selected.value.push(q.id);else if(selected.value.length>=3){toast.value=t('toast.maxCompare');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.value='',3000);}close();}
function visible(){if(document.visibilityState==='visible')void load();}
onMounted(()=>{const raw:Record<string,unknown>={};for(const [key,value] of new URLSearchParams(location.search)){if(key==='utilization')continue;raw[key]=['budget','upfrontBudget','minRank','minTokensPerSecond','apiSpendUSD','context'].includes(key)?Number(value):key==='allowAnnual'?value==='true':value;}const parsed=ValuePreferencesSchema.safeParse(raw);if(parsed.success)prefs.value=parsed.data;void load();clock=setInterval(()=>now.value=Date.now(),1000);refresh=setInterval(()=>void load(),60000);document.addEventListener('visibilitychange',visible);});
onBeforeUnmount(()=>{clearTimeout(debounce);clearTimeout(toastTimer);clearInterval(clock);clearInterval(refresh);document.removeEventListener('visibilitychange',visible);});
watch(prefs,()=>{clearTimeout(debounce);debounce=setTimeout(()=>void search(),180);},{deep:true});
watch(tab,()=>window.scrollTo({top:0,behavior:'instant'}));
const navItems:[string,UiKey][]=[['value','nav.value'],['status','nav.status']];
</script>
<template><a class="skip-link" href="#main">{{t('app.skipLink')}}</a><div class="app-shell"><header class="topbar"><a class="wordmark" href="/" :aria-label="t('app.home')"><img src="/brand/6yuwei-3d-white.png" alt="" width="40" height="40"><span>atlas.</span></a><nav class="main-nav" :aria-label="t('app.mainMenu')"><button v-for="[id,key] in navItems" :key="id" :class="{active:tab===id}" :aria-current="tab===id?'page':undefined" @click="tab=id">{{t(key)}}</button></nav><button class="verified-status" @click="tab='status'"><span class="status-dot"></span>{{t('topbar.verified')}} <span>{{checkedDate}}</span></button><button class="lang-switch" @click="toggleLocale()">{{t('lang.switch')}}</button></header><main id="main"><div v-if="error" role="alert" class="error-banner">{{error}}{{t('error.keepFresh')}}<button @click="load">{{t('error.retry')}}</button></div><template v-if="tab==='value'"><ValueFilters v-model="prefs" :catalog="catalog" @reset="reset"/><ValueList :catalog="catalog" :data="results" :busy="busy" :now="now" @detail="q=>detail=[q]" @unknown="p=>detailPlan=p" @reset="reset" @method="method=true"/></template><DataStatusView v-else-if="catalog" :catalog="catalog" @detail="p=>detailPlan=p"/><p v-else class="empty-state">{{t('app.loading')}}</p></main><footer class="site-footer"><button class="footer-method" @click="method=true">{{t('footer.method')}}</button><div><span>{{t('footer.sources')}}</span><a href="https://docs.z.ai/devpack/overview" target="_blank" rel="noopener noreferrer">Z.ai</a><span>·</span><a href="https://opencode.ai/docs/go/" target="_blank" rel="noopener noreferrer">OpenCode</a><span>·</span><a href="https://arena.ai/leaderboard/agent/" target="_blank" rel="noopener noreferrer">{{t('bench.general')}}</a><span>·</span><a href="https://arena.ai/leaderboard/agent/code" target="_blank" rel="noopener noreferrer">Coding</a><span>·</span><a href="https://arena.ai/leaderboard/code/webdev" target="_blank" rel="noopener noreferrer">WebDev</a><span>·</span><a href="https://arena.ai/leaderboard/code/webdev/frontend" target="_blank" rel="noopener noreferrer">Frontend</a></div></footer></div><div v-if="comparable.length" class="compare-tray"><span>{{t('tray.selected',{n:comparable.length})}}</span><button v-for="q in comparable" :key="q.id" class="compare-chip" :aria-label="t('tray.remove',{label:`${q.model.name} ${td(q.offer.label)}`})" @click="selected=selected.filter(id=>id!==q.id)">{{q.model.name}} · {{td(q.offer.label)}} ×</button><button class="solid-button" @click="detail=comparable">{{t('tray.compare')}}</button><button class="icon-button" :aria-label="t('tray.clear')" @click="selected=[]">×</button></div><ValueDialog v-if="hasDialog&&detailCatalog" :items="detail" :plan="detailPlan" :catalog="detailCatalog" :method="method" @close="close" @compare="compare"/><div v-if="toast" class="toast" role="status">{{toast}}</div></template>
